### ISSUE TITLE
UI issue after escort mission completed

### ISSUE THREAD

**Issue by matthieudesprez** [thunderk/spacetac#4]
To reproduce : Complete escort mission (doesn't happen with the first ones, maybe on already visited planets)
Issue : the escorted ship still appears in the UI

![image](https://user-images.githubusercontent.com/13304634/28221288-08804e1e-68c3-11e7-8b80-87cb9f7fb763.png)

When the inventory is opened, if the escorted ship is clicked, a glitch appears :

![image](https://user-images.githubusercontent.com/13304634/28221464-a37cb0e2-68c3-11e7-9176-2df7f998062c.png)

**Comment by thunderk** [comment]
Fixed in 81f7174b588f34c2514481a9b603629d58bad5d6
