### ISSUE TITLE
Incorrect Ship Level in battle tooltip and inventory screen

### ISSUE THREAD

**Issue by matthieudesprez** [thunderk/spacetac#5]
The ship is level 4 but the tooltip and the inventory title still display "level 1"
![image](https://user-images.githubusercontent.com/13304634/28798481-e4579512-7644-11e7-8b0e-27e3eda79a07.png)
![image](https://user-images.githubusercontent.com/13304634/28798493-f1bb7be2-7644-11e7-9512-6db48f2d2e4a.png)

**Comment by thunderk** [comment]
Fixed in ff233bd16458efadd96368f278d7371564489ef9
