### ISSUE TITLE
Missing avatar in dialogs for escorted ship

### ISSUE THREAD

**Issue by matthieudesprez** [thunderk/spacetac#6]
this one : 
![image](https://user-images.githubusercontent.com/13304634/28798746-b5590bdc-7645-11e7-9aad-b39469c29b34.png)

does not appear in the dialog box :
![image](https://user-images.githubusercontent.com/13304634/28798667-7fb0d35c-7645-11e7-9295-55fe0218bef1.png)

**Comment by thunderk** [comment]
Fixed in dd37f20a43e2c0c1bf93f0c0e87cde4c9ec7f302
